-- Nacos PostgreSQL Schema
-- 来源：Nacos v3.2.2 mysql-schema.sql 转换为 PostgreSQL
-- 用法：手动导入 PG 的 nacos 数据库
--       psql -h localhost -U postgres -d nacos -f nacos-schema.sql

-- =========== config_info ===========
CREATE TABLE IF NOT EXISTS config_info (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_id             VARCHAR(255) NOT NULL,
    group_id            VARCHAR(128) DEFAULT NULL,
    content             TEXT NOT NULL,
    md5                 VARCHAR(32) DEFAULT NULL,
    gmt_create          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    src_user            TEXT,
    src_ip              VARCHAR(50) DEFAULT NULL,
    app_name            VARCHAR(128) DEFAULT NULL,
    tenant_id           VARCHAR(128) NOT NULL DEFAULT '',
    c_desc              VARCHAR(256) DEFAULT NULL,
    c_use               VARCHAR(64) DEFAULT NULL,
    effect              VARCHAR(64) DEFAULT NULL,
    type                VARCHAR(64) DEFAULT NULL,
    c_schema            TEXT,
    encrypted_data_key  VARCHAR(1024) NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_configinfo_datagrouptenant
    ON config_info(data_id, group_id, tenant_id);

-- =========== config_info_gray (since 2.5.0) ===========
CREATE TABLE IF NOT EXISTS config_info_gray (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_id             VARCHAR(255) NOT NULL,
    group_id            VARCHAR(128) NOT NULL,
    content             TEXT NOT NULL,
    md5                 VARCHAR(32) DEFAULT NULL,
    src_user            TEXT,
    src_ip              VARCHAR(100) DEFAULT NULL,
    gmt_create          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    app_name            VARCHAR(128) DEFAULT NULL,
    tenant_id           VARCHAR(128) NOT NULL DEFAULT '',
    gray_name           VARCHAR(128) NOT NULL,
    gray_rule           TEXT NOT NULL,
    encrypted_data_key  VARCHAR(256) NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_configinfogray_datagrouptenantgray
    ON config_info_gray(data_id, group_id, tenant_id, gray_name);
CREATE INDEX IF NOT EXISTS idx_dataid_gmt_modified
    ON config_info_gray(data_id, gmt_modified);
CREATE INDEX IF NOT EXISTS idx_gmt_modified
    ON config_info_gray(gmt_modified);

-- =========== config_tags_relation ===========
CREATE TABLE IF NOT EXISTS config_tags_relation (
    id          BIGINT NOT NULL,
    tag_name    VARCHAR(128) NOT NULL,
    tag_type    VARCHAR(64) DEFAULT NULL,
    data_id     VARCHAR(255) NOT NULL,
    group_id    VARCHAR(128) NOT NULL,
    tenant_id   VARCHAR(128) NOT NULL DEFAULT '',
    nid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_configtagrelation_configidtag
    ON config_tags_relation(id, tag_name, tag_type);
CREATE INDEX IF NOT EXISTS idx_tenant_id
    ON config_tags_relation(tenant_id);

-- =========== group_capacity ===========
CREATE TABLE IF NOT EXISTS group_capacity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id            VARCHAR(128) NOT NULL DEFAULT '',
    quota               INT NOT NULL DEFAULT 0,
    usage               INT NOT NULL DEFAULT 0,
    max_size            INT NOT NULL DEFAULT 0,
    max_aggr_count      INT NOT NULL DEFAULT 0,
    max_aggr_size       INT NOT NULL DEFAULT 0,
    max_history_count   INT NOT NULL DEFAULT 0,
    gmt_create          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_group_id
    ON group_capacity(group_id);

-- =========== his_config_info ===========
CREATE TABLE IF NOT EXISTS his_config_info (
    id                  BIGINT NOT NULL,
    nid                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_id             VARCHAR(255) NOT NULL,
    group_id            VARCHAR(128) NOT NULL,
    app_name            VARCHAR(128) DEFAULT NULL,
    content             TEXT NOT NULL,
    md5                 VARCHAR(32) DEFAULT NULL,
    gmt_create          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    src_user            TEXT,
    src_ip              VARCHAR(50) DEFAULT NULL,
    op_type             CHAR(10) DEFAULT NULL,
    tenant_id           VARCHAR(128) NOT NULL DEFAULT '',
    encrypted_data_key  VARCHAR(1024) NOT NULL DEFAULT '',
    publish_type        VARCHAR(50) DEFAULT 'formal',
    gray_name           VARCHAR(50) DEFAULT NULL,
    ext_info            TEXT DEFAULT NULL
);
CREATE INDEX IF NOT EXISTS idx_gmt_create ON his_config_info(gmt_create);
CREATE INDEX IF NOT EXISTS idx_gmt_modified ON his_config_info(gmt_modified);
CREATE INDEX IF NOT EXISTS idx_did ON his_config_info(data_id);

-- =========== tenant_capacity ===========
CREATE TABLE IF NOT EXISTS tenant_capacity (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           VARCHAR(128) NOT NULL DEFAULT '',
    quota               INT NOT NULL DEFAULT 0,
    usage               INT NOT NULL DEFAULT 0,
    max_size            INT NOT NULL DEFAULT 0,
    max_aggr_count      INT NOT NULL DEFAULT 0,
    max_aggr_size       INT NOT NULL DEFAULT 0,
    max_history_count   INT NOT NULL DEFAULT 0,
    gmt_create          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_tenant_id
    ON tenant_capacity(tenant_id);

-- =========== tenant_info ===========
CREATE TABLE IF NOT EXISTS tenant_info (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kp              VARCHAR(128) NOT NULL,
    tenant_id       VARCHAR(128) NOT NULL DEFAULT '',
    tenant_name     VARCHAR(128) DEFAULT '',
    tenant_desc     VARCHAR(256) DEFAULT NULL,
    create_source   VARCHAR(32) DEFAULT NULL,
    gmt_create      BIGINT NOT NULL,
    gmt_modified    BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_tenant_info_kptenantid
    ON tenant_info(kp, tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_id2
    ON tenant_info(tenant_id);

-- =========== users ===========
CREATE TABLE IF NOT EXISTS users (
    username    VARCHAR(50) NOT NULL PRIMARY KEY,
    password    VARCHAR(500) NOT NULL,
    enabled     BOOLEAN NOT NULL
);

-- =========== roles ===========
CREATE TABLE IF NOT EXISTS roles (
    username    VARCHAR(50) NOT NULL,
    role        VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_role
    ON roles(username, role);

-- =========== permissions ===========
CREATE TABLE IF NOT EXISTS permissions (
    role        VARCHAR(50) NOT NULL,
    resource    VARCHAR(128) NOT NULL,
    action      VARCHAR(8) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_role_permission
    ON permissions(role, resource, action);

-- =========== pipeline_execution (v3.x AI) ===========
CREATE TABLE IF NOT EXISTS pipeline_execution (
    execution_id    VARCHAR(64) NOT NULL PRIMARY KEY,
    resource_type   VARCHAR(32) NOT NULL,
    resource_name   VARCHAR(256) NOT NULL,
    namespace_id    VARCHAR(128) DEFAULT NULL,
    version         VARCHAR(64) DEFAULT NULL,
    status          VARCHAR(32) NOT NULL,
    pipeline        TEXT NOT NULL,
    create_time     BIGINT NOT NULL,
    update_time     BIGINT NOT NULL
);

-- =========== ai_resource (v3.x AI) ===========
CREATE TABLE IF NOT EXISTS ai_resource (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gmt_create      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name            VARCHAR(256) NOT NULL,
    type            VARCHAR(32) NOT NULL,
    c_desc          VARCHAR(2048) DEFAULT NULL,
    status          VARCHAR(32) DEFAULT NULL,
    namespace_id    VARCHAR(128) NOT NULL DEFAULT '',
    biz_tags        VARCHAR(1024) DEFAULT NULL,
    ext             TEXT DEFAULT NULL,
    c_from          VARCHAR(256) NOT NULL DEFAULT 'local',
    version_info    TEXT DEFAULT NULL,
    meta_version    BIGINT NOT NULL DEFAULT 1,
    scope           VARCHAR(16) NOT NULL DEFAULT 'PRIVATE',
    owner           VARCHAR(128) NOT NULL DEFAULT '',
    download_count  BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_resource_ns_name_type
    ON ai_resource(namespace_id, name, type, c_from);
CREATE INDEX IF NOT EXISTS idx_ai_resource_name ON ai_resource(name);
CREATE INDEX IF NOT EXISTS idx_ai_resource_type ON ai_resource(type);
CREATE INDEX IF NOT EXISTS idx_ai_resource_gmt_modified ON ai_resource(gmt_modified);

-- =========== ai_resource_version (v3.x AI) ===========
CREATE TABLE IF NOT EXISTS ai_resource_version (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gmt_create              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type                    VARCHAR(32) NOT NULL,
    author                  VARCHAR(128) DEFAULT NULL,
    name                    VARCHAR(256) NOT NULL,
    c_desc                  VARCHAR(2048) DEFAULT NULL,
    status                  VARCHAR(32) NOT NULL,
    version                 VARCHAR(64) NOT NULL,
    namespace_id            VARCHAR(128) NOT NULL DEFAULT '',
    storage                 TEXT DEFAULT NULL,
    publish_pipeline_info   TEXT DEFAULT NULL,
    download_count          BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_resource_ver_ns_name_type_ver
    ON ai_resource_version(namespace_id, name, type, version);
CREATE INDEX IF NOT EXISTS idx_ai_resource_ver_name ON ai_resource_version(name);
CREATE INDEX IF NOT EXISTS idx_ai_resource_ver_status ON ai_resource_version(status);
CREATE INDEX IF NOT EXISTS idx_ai_resource_ver_gmt_modified ON ai_resource_version(gmt_modified);
