spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/aim?currentSchema=%22user%22&stringtype=unspecified
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  expire-sec: 7200
  refresh-sec: 2592000
